### PR TITLE
fix timings for transition frame

### LINKED ISSUE #135: Laggy animated wallpapers and leaving artifacts
After updating to the latest version: `swww 0.8.0-master`, my .gif has been laggy and glitchy.
Here's the command I use:
```bash
swww img --filter Nearest MemoryOfaDistantPlace.gif
```
I attached the gif below
MemoryOfaDistantPlace
image

### LINKED ISSUE #154: Changing wallpaper now looks laggy.
Hi, I don't know how I should debug this.
I'm on Arch Linux, and just updated swww to 0.8.1-0.
It was working fine (and still does) but for some reason now when I animate the wallpaper transition it looks really laggy and fades without closing the circle at the end. Here is a recording:

https://github.com/Horus645/swww/assets/96461803/eeed06f5-da94-46a3-8b12-24dde8bb3aca

It used to work just like in the README.md
I'm using this command:
swww img -t any --transition-bezier 0.0,0.0,1.0,1.0 --transition-duration .75 --transition-step 255 --transition-fps 60 /path/to/wallpaper

### PR DESCRIPTION
**Pull request by Horus645**
Fixes #154 .

### CODE REVIEW

**Comment by AdrianoTisera** [comment]
Thanks! I'll wait for the merge. :)

**Comment by Horus645** [comment]
Just an update: I've been running into some rare issues with this that I haven't had time to troubleshoot yet (especially because they don't _always_ happen)

**Comment by Readf0x** [comment]
any updates on this? @Horus645 (sorry for the @ but I really want this to get fixed)

**Review by Readf0x — APPROVED** [review]

**Comment by Readf0x** [comment]
whoops did not mean to do that but oh well

**Comment by Horus645** [comment]
Hello. Sorry for the late reply. 

@Readf0x could you maybe take this for a ride, then? Check to see if it causes any major problems on your end. It's actually been fine for me, but I no longer have a two monitor setup, so I don't know what kind of weirdness might happen in those cases.

**Comment by Seme4eg** [comment]
works great for me with my scaled hidpi screen!
will test today on double-monitor setup

**Comment by Seme4eg** [comment]
can't / don't know how to record both screens with wf-recorder to demonstrate, but anyway, on 2-monitor setup (1st - laptop, 4k, 1.7 scaled, hidpi, 2nd - 2k 144hz non-scaled) works flawlessly now. Pushed it hard, no crashes or stutters.

**Comment by Readf0x** [comment]
Actually, I've been using this, merged with the latest commit on main (at
least back when I had sent that message) since there were no conflicts.
Works perfectly fine.

**Pull request merged**
