### PR TITLE
Sync outputs

### LINKED ISSUE #39: Span image over all monitors.
Would it be possible to allow an image to be spanned over multiple monitors?
I could try to implement this myself. I would just need a hint, where in the code the image is drawn on a specific output.
I gues I would just need to split the image data into `n` chunks and then send them to the appropriate outputs.

### PR DESCRIPTION
**Pull request by Horus645**
Fixes #39.

Sorry it took so long, @FF-AntiK. This turned out to be a lot more annoying than I expected. Hopefully this solution here is good enough.

### CODE REVIEW

**Comment by Horus645** [comment]
Oops, I tried running this on my notebook and discovered that I forgot to `git add` a file :facepalm:

**Comment by FF-AntiK** [comment]
Hi @Horus645 ,
thank you very much for working on this.
I've tried this branch, but it gives me the error when sending an image to any monitor (both with and without `--sync`):
`Error: "Failed to receive answer: io error: Resource temporarily unavailable (os error 11)"`

**Comment by Horus645** [comment]
@FF-AntiK did you by any chance test it by rnning `./target/release/swww init`? Note in that `swww` will use the `swww-daemon` binary in your `$PATH`. Since we changed the daemon in this PR, in order to test it, you'll have to start the daemon manually with `./target/release/swww-daemon`, and *then* use `./target/release/swww img` to set the wallpapers. Annoying, I know, but I am not sure what to do about this.

**Comment by FF-AntiK** [comment]
Oh, it's possible, that I've only built `swww` and didn't update `swww-daemon`. As soon as I have time to test it agein I'll let you know :-)

**Comment by FF-AntiK** [comment]
I've tested it now and it works great!
Thanks again for your excelent work! :-)

**Pull request merged**
